Messages:
  blocked-command: "&6&lVoltz&f&lMC &8&l➜ &cEsse comando não existe!"

Whitelisted-Admins:
  - 'zPG0D'

Blocked-Commands:
  - '/cash give'
  - '/cash set'
  - '/we'
  - '/worldedit'
  - '/fawe'
  - '/plugman'
  - '/tellraw'
  - '/stop'
  - '/reload'
  - '/rl'
  - '/restart'
  - '/pex'
  - '/promote'
  - '/demote'
  - '/chestcommands'
  - '/combatlogx'
  - '/combattime'
  - '/sp'
  - '/ea'
  - '/hd'
  - '/holograms'
  - '/holographicdisplays'
  - '/darvip'
  - '/rvip'
  - '/us'
  - '/ultimatestacker'
  - '/stacker'
  - '//calc'
  - '//calculate'
  - '//eval'
  - '//evaluate'
  - '//solve'
  - '/npc'
  - '/npcmd'
  - '/citizens'
  - '/enchant'
  - '/encantar'
  - '/looting'
  - '/rc'